# permissions for end users to edit ngroks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ngrok-editor-role
rules:
- apiGroups:
  - ngrok.com
  resources:
  - ngroks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ngrok.com
  resources:
  - ngroks/status
  verbs:
  - get
