---
apiVersion: v2
name: ngrok-operator
description: ngrok-operator for managing ngrok lifecycle
version: 1.0.0
appVersion: 1.0.0
type: application
home: https://github.com/zufardhiyaulhaq/ngrok-operator

maintainers:
- name: Zufar Dhiyaulhaq
  email: zufardhiyaulhaq@gmail.com
  url: https://zufardhiyaulhaq.com
